import{a as c,S as M,i}from"./assets/vendor-b42c18af.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))l(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&l(n)}).observe(document,{childList:!0,subtree:!0});function u(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function l(t){if(t.ep)return;t.ep=!0;const o=u(t);fetch(t.href,o)}})();const d={value:""},a={value:1},f=40;c.defaults.baseURL="https://pixabay.com/api/";c.defaults.params={key:"22046149-41a2515b5a783e6a5f4bfbfcc",per_page:f,image_type:"photo",orientation:"horizontal",safesearch:!0};async function g(e){try{return(await c.get("/",{params:{...c.defaults.params,q:e,page:a.value}})).data}catch{throw new Error("An error occurred while fetching images.")}}const S=document.getElementById("search-form"),p=document.querySelector(".gallery"),m=document.querySelector(".load-more"),y=new M(".gallery a");S.addEventListener("submit",$);m.addEventListener("click",q);let s=0;async function $(e){e.preventDefault(),b(),a.value=1,s=0;const r=e.currentTarget.elements.searchQuery.value.trim();if(d.value=r,d.value===""){v("⁉️ Please enter your search query.");return}B(),await h(),H()}async function h(){try{const e=await g(d.value);if(e.hits.length===0){I();return}s=e.totalHits,P(e.hits),s>0&&a.value===1&&w()}catch(e){v(e.message)}}function q(){a.value+=1,h(),setTimeout(()=>{const{height:e}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})},500)}function P(e){const r=e.map(({webformatURL:l,likes:t,views:o,comments:n,downloads:L,largeImageURL:E,tags:O})=>`
      <a class="card-item" href="${E}" data-lightbox="gallery-item" aria-role="button" >
      <div class="card-box">
            <img src="${l}" class="card-img" alt="${O}" loading="lazy" />
            </div>
            <div class="info">
            <p class="info-item">
            <b>likes</b> ${t}</p>
            <p class="info-item">
            <b>views</b> ${o}</p>
            <p class="info-item">
            <b>comments</b> ${n}</p>
            <p class="info-item"><b>downloads</b> ${L}</p>
            </div>
            </a>`).join("");p.insertAdjacentHTML("beforeend",r),y.refresh();const u=a.value*f;s<=u&&(b(),x())}function B(){p.innerHTML=""}function H(){const e=a.value*f,r=s<=e;m.style.display=r?"none":"block",w.enabled=!r,r||y.refresh()}function b(){m.style.display="none"}function v(e){i.error({message:e})}function w(){i.success({message:`🎉 Hooray! We found ${s} images.`})}function I(){i.warning({message:"🧐 Sorry, there are no images matching your search query. Please try again."})}function x(){setTimeout(()=>{i.info({message:`We're sorry, but you've reached the end of ${s} search results.`,position:"bottomCenter",timeout:4e3})},4e3)}i.settings({messageColor:"rgb(22, 24, 61)",position:"topRight",timeout:2500,closeOnEscape:!0,animateInside:!0,drag:!0,pauseOnHover:!0,progressBarEasing:"linear",overlay:!1,overlayClose:!1,overlayColor:"rgba(0, 0, 0, 0.6)",icon:"material-icons",transitionIn:"flipInX",transitionOut:"flipOutX"});console.log(g());
//# sourceMappingURL=commonHelpers.js.map
